import type { Metadata } from "next";
import "../styles/globals.css";
import "../styles/fonts.css";
import { Footer } from "./_components/footer";
import { Navbar } from "./_components/navbar";
import { ShoppingCartProvider } from "@/context/shopping-cart";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Pj Ferragens",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased font-noto">
        <ShoppingCartProvider>
          <Navbar />
          {children}
        </ShoppingCartProvider>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
